### ISSUE TITLE
Fail to compile because VM (qemu) does not set up internet connection

### ISSUE THREAD

**Issue by marcelogaio** [tingbot/sdcard#1]
root@raspberrypi:/apps# ifconfig
eth0      Link encap:Ethernet  HWaddr 52:54:00:12:34:56
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:57 Base address:0x8000 DMA chan:ff

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

root@raspberrypi:/apps# ping google.com
ping: unknown host google.com
root@raspberrypi:/apps#

**Comment by joerick** [comment]
I've not seen this problem myself - do you know if your qemu might have different defaults to mine? I'm running it on a homebrew-installed version on Mac.

**Comment by marcelogaio** [comment]
I am also working on Mac w/homebrew. The installation is brand new (installed ElCapitan from scratch on a new disk)

Steps I followed:
- I installed quemu the normal way:
```
brew install qemu
```
- After that, I generated a new folder (Git/tingbot) and got the GIT:
```
git clone https://github.com/tingbot/sdcard.git
```
- Then, changed into the Git/tingbot/sdcard and ran:
```
make
```

After the img download, I noticed the VM started, did some stuff, restarted again, and then it was trying to run an apt-get, but it failed because there was no connection...

**UPDATE:**
I just ran it again, the same way (but now the IMG was already on disk so that step was skipped) and now it seems to be working fine... It ran the apt-get installs and now is compiling (long time)

I'll try again on a fresh install and document the whole output, in case it fails again.

**Comment by marcelogaio** [comment]
Worked fine when I tried again from scratch. Issue closed!

**Comment by joerick** [comment]
Great! Must have been some temporary network issue.
